import { Proyecto } from "./types";

export const proyectosMock: Proyecto[] = [
  {
    id: "1",
    nombre: "Ampliación Red de Agua Potable - Sector La Victoria",
    tipo: "sgo",
    descripcion:
      'Proyecto de ampliación de la red de distribución de agua potable en el sector La Victoria, incluyendo instalación de tuberías de PVC de 4" y 6" para mejorar la cobertura del servicio.',
    fecha: "2026-01-15",
    ingenieroSupervisor: "Ing. Carlos Mendoza López",
    registradoPor: "Ana García Ríos",
    area: "Gerencia de Proyectos y Obras",
    empresaEjecutora: "Constructora Hidráulica del Norte S.A.C.",
    conexionesDomiciliares: 320,
    metrosLinealesAgua: 4500,
    metrosLinealesAlcantarillado: 0,
    costoProyecto: 1250000,
    archivos: [
      { id: "a1", nombre: "Plano_General.pdf", tipo: "pdf", url: "#" },
      { id: "a2", nombre: "Fotos_Avance.jpg", tipo: "jpg", url: "#" },
    ],
  },
  {
    id: "2",
    nombre: "Mantenimiento Red Alcantarillado - Av. Bolognesi",
    tipo: "servicio",
    descripcion:
      "Servicio de mantenimiento preventivo y correctivo de la red de alcantarillado en la Av. Bolognesi, incluyendo limpieza de buzones y reparación de tuberías colapsadas.",
    fecha: "2026-02-20",
    ingenieroSupervisor: "Ing. María Fernández Castillo",
    registradoPor: "Luis Pérez Díaz",
    area: "Gerencia Operacional",
    empresaEjecutora: "Servicios Sanitarios del Perú E.I.R.L.",
    conexionesDomiciliares: 0,
    metrosLinealesAgua: 0,
    metrosLinealesAlcantarillado: 2800,
    costoProyecto: 380000,
    archivos: [
      { id: "a3", nombre: "Informe_Tecnico.pdf", tipo: "pdf", url: "#" },
    ],
  },
  {
    id: "3",
    nombre: "Instalación de Conexiones Domiciliarias - Urb. Santa Rosa",
    tipo: "sge",
    descripcion:
      "Obra de instalación de conexiones domiciliarias de agua potable y alcantarillado en la urbanización Santa Rosa, beneficiando a 150 familias del sector.",
    fecha: "2026-03-10",
    ingenieroSupervisor: "Ing. Roberto Sánchez Vega",
    registradoPor: "Carmen Torres Llontop",
    area: "Gerencia Comercial",
    empresaEjecutora: "Grupo Constructor Lambda S.A.",
    conexionesDomiciliares: 150,
    metrosLinealesAgua: 2100,
    metrosLinealesAlcantarillado: 1800,
    costoProyecto: 740000,
    archivos: [
      { id: "a4", nombre: "Expediente_Tecnico.rar", tipo: "rar", url: "#" },
      { id: "a5", nombre: "Plano_Conexiones.pdf", tipo: "pdf", url: "#" },
      { id: "a6", nombre: "Foto_Inicio.jpg", tipo: "jpg", url: "#" },
    ],
  },
  {
    id: "4",
    nombre: "Reparación de Fuga - Jr. San Martín Cdra. 5",
    tipo: "servicio",
    descripcion:
      'Servicio de emergencia para la reparación de fuga en tubería principal de agua potable de 8" en el Jr. San Martín, cuadra 5.',
    fecha: "2026-03-25",
    ingenieroSupervisor: "Ing. Pedro Villanueva Rojas",
    registradoPor: "José Ramírez Cruz",
    area: "Gerencia Operacional",
    empresaEjecutora: "EPSEL S.A. (Ejecución Directa)",
    conexionesDomiciliares: 0,
    metrosLinealesAgua: 45,
    metrosLinealesAlcantarillado: 0,
    costoProyecto: 55000,
    archivos: [
      { id: "a7", nombre: "Reporte_Emergencia.pdf", tipo: "pdf", url: "#" },
    ],
  },
  {
    id: "5",
    nombre: "Construcción Reservorio R-12 - Sector Nor Este",
    tipo: "elaboracion_tdr",
    descripcion:
      "Construcción de reservorio elevado de 500 m³ de capacidad para abastecer al sector nor este de la ciudad, incluyendo línea de aducción y red de distribución.",
    fecha: "2025-11-05",
    ingenieroSupervisor: "Ing. Fernando Delgado Quiroz",
    registradoPor: "Ana García Ríos",
    area: "Gerencia de Proyectos y Obras",
    empresaEjecutora: "Consorcio Agua Norte",
    conexionesDomiciliares: 800,
    metrosLinealesAgua: 12000,
    metrosLinealesAlcantarillado: 0,
    costoProyecto: 3150000,
    archivos: [
      { id: "a8", nombre: "Expediente_Completo.rar", tipo: "rar", url: "#" },
      { id: "a9", nombre: "Presupuesto.pdf", tipo: "pdf", url: "#" },
    ],
  },
  {
    id: "6",
    nombre: "Limpieza de Cámaras de Bombeo - Zona Sur",
    tipo: "servicio",
    descripcion:
      "Servicio de limpieza y mantenimiento de 5 cámaras de bombeo de aguas residuales en la zona sur, incluyendo revisión de equipos electromecánicos.",
    fecha: "2026-03-01",
    ingenieroSupervisor: "Ing. María Fernández Castillo",
    registradoPor: "Luis Pérez Díaz",
    area: "Gerencia Operacional",
    empresaEjecutora: "Mantenimiento Industrial del Norte S.R.L.",
    conexionesDomiciliares: 0,
    metrosLinealesAgua: 0,
    metrosLinealesAlcantarillado: 350,
    costoProyecto: 92000,
    archivos: [],
  },
];
